version: '3.8'
services:
  backend:
    build: ./docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
    depends_on:
      - mysql
      - mongodb
      
  frontend:
    build: ./docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
      
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: taskflow
      
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"